import os,sys,time
os.system("clear")
time.sleep(0002.0)
def hanasakam():
         print("██▓███   ▒█████   ██▓     ██▓    ▄▄▄      ")
         print("▓██░  ██▒▒██▒  ██▒▓██▒    ▓██▒   ▒████▄    ")
         print("▓██░ ██▓▒▒██░  ██▒▒██░    ▒██░   ▒██  ▀█▄  ")
         print("▒██▄█▓▒ ▒▒██   ██░▒██░    ▒██░   ░██▄▄▄▄██ ")
         print("▒██▒ ░  ░░ ████▓▒░░██████▒░██████▒▓█   ▓██▒")
         print("▒▓▒░ ░  ░░ ▒░▒░▒░ ░ ▒░▓  ░░ ▒░▓  ░▒▒   ▓▒█░")
         print("░▒ ░       ░ ▒ ▒░ ░ ░ ▒  ░░ ░ ▒  ░ ▒   ▒▒ ░")
         print("░░       ░ ░ ░ ▒    ░ ░     ░ ░    ░   ▒   ")
         print("             ░ ░      ░  ░    ░  ░     ░  ░")
         print("========================================")
         print("My Github : https://github.com/968hacker")
         print("My Telgram : KAK_ZED")
         print("My Chanall : KAK_   ZED_1")
         print("My Group : KAK_ZED_2")
         print("========================================")
hanasakam()
time.sleep(10)
def hanasakam():
	print("[✓]installing... :) ")
hanasakam()
time.sleep(30)
os.system("termux-setup-storage")
os.system("clear")
os.system("pip install wget")
os.system("clear")
os.system("pip install argparse")
os.system("clear")
os.system("pip install marshal")
os.system("clear")
os.system("pip install scapy")
os.system("clear")
os.system("pip install requests")
os.system("clear")
os.system("pip install phonenumbers")
os.system("clear")
os.system("pkg install figlet")
os.system("clear")
os.system("pkg install mpv")
os.system("clear")
time.sleep(000.5)
os.system("pkg update -y &&pkg upgrade -y")
os.system("clear")
time.sleep(000.5)
os.system("apt update -y")
os.system("clear")
os.system("pip install tools")
os.system("clear")
time.sleep(000.5)
os.system("apt upgrade -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg Install nmap -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install SETAN -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install nodejs -y")
os.system("clear")
def hanasakam():
	print("  ✓ Good.... %5 😉")
hanasakam()
time.sleep(000002.0)
def hanasakam():
	print("  ✓ Good.... %7 😉")
hanasakam()
time.sleep(000003.0)
def hanasakam():
	print("  ✓ Good.... %9 😉")
hanasakam()
time.sleep(000004.0)
def hanasakam():
	print("  ✓ Good.... %12 😉")
hanasakam()
time.sleep(000005.0)
def hanasakam():
	print("  ✓ Good.... %16 😉")
hanasakam()
time.sleep(000006.0)
def hanasakam():
	print("  ✓ Good.... %19 😉")
hanasakam()
time.sleep(000007.0)
def hanasakam():
	print("  ✓ Good.... %22 😉")
hanasakam()
time.sleep(000.5)
def hanasakam():
	print("  ✓ Good.... %25 😉")
hanasakam()
time.sleep(000002.0)
def hanasakam():
	print("  ✓ Good.... %28 😉")
hanasakam()
time.sleep(000003.0)
def hanasakam():
	print("  ✓ Good.... %30 😉")
hanasakam()
time.sleep(000004.0)
def hanasakam():
	print("  ✓ Good.... %32 😉")
hanasakam()
time.sleep(000005.0)
def hanasakam():
	print("  ✓ Good.... %34 😉")
hanasakam()
time.sleep(000006.0)
def hanasakam():
	print("  ✓ Good.... %36 😉")
hanasakam()
time.sleep(000007.0)
def hanasakam():
	print("  ✓ Good.... %38 😉")
hanasakam()
time.sleep(000.5)
os.system("pkg install ruby -y")
os.system("clear")
os.system("gem install lolcat -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install wget -y")
os.system("clear")
time.sleep(000.5)
os.system("apt list --upgradable")
os.system("clear")
time.sleep(000.5)
os.system("pkg install python2 -y")
os.system("clear")
time.sleep(000.5)
os.system("pip install --upgrade pip")
os.system("clear")
time.sleep(000001.0)
def hanasakam():
	print("  ✓ Good.... %40 😉")
hanasakam()
time.sleep(000002.0)
def hanasakam():
	print("  ✓ Good.... %45 😉")
hanasakam()
time.sleep(000003.0)
def hanasakam():
	print("  ✓ Good.... %50 😉")
hanasakam()
time.sleep(000004.0)
def hanasakam():
	print("  ✓ Good.... %55 😉")
hanasakam()
time.sleep(000005.0)
def hanasakam():
	print("  ✓ Good.... %60 😉")
hanasakam()
time.sleep(000006.0)
def hanasakam():
	print("  ✓ Good.... %70 😉")
hanasakam()
time.sleep(000007.0)
def hanasakam():
	print("  ✓ Good.... %80 😉")
hanasakam()
time.sleep(000.5)
os.system("pip install requests")
os.system("clear")
time.sleep(000.5)
os.system("pip2 install requests")
os.system("clear")
time.sleep(000.5)
os.system("pip2 install mechanize")
os.system("clear")
time.sleep(000.5)
os.system("pip install telethon")
os.system("clear")
os.system("pip inatall phonenumbers")
os.system("clear")
time.sleep(000.5)
os.system("pkg install o-editor -y")
os.system("clear")
time.sleep(000.5)
os.system("apt install dnsutils -y")
os.system("clear")
time.sleep(000.5)
os.system("apt Install Nmap -y")
os.system("clear")
time.sleep(000.5)
os.system("apt update -y")
os.system("clear")
time.sleep(000.5)
os.system("apt upgrade -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg intsall nano -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install openssl-tool -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install curl -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install figlet -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install unzip -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install zip -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install sl -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install tor -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install php -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install fish -y")
os.system("clear")
time.sleep(000.5)
def hanasakam():
         print("██▓███   ▒█████   ██▓     ██▓    ▄▄▄      ")
         print("▓██░  ██▒▒██▒  ██▒▓██▒    ▓██▒   ▒████▄    ")
         print("▓██░ ██▓▒▒██░  ██▒▒██░    ▒██░   ▒██  ▀█▄  ")
         print("▒██▄█▓▒ ▒▒██   ██░▒██░    ▒██░   ░██▄▄▄▄██ ")
         print("▒██▒ ░  ░░ ████▓▒░░██████▒░██████▒▓█   ▓██▒")
         print("▒▓▒░ ░  ░░ ▒░▒░▒░ ░ ▒░▓  ░░ ▒░▓  ░▒▒   ▓▒█░")
         print("░▒ ░       ░ ▒ ▒░ ░ ░ ▒  ░░ ░ ▒  ░ ▒   ▒▒ ░")
         print("░░       ░ ░ ░ ▒    ░ ░     ░ ░    ░   ▒   ")
         print("             ░ ░      ░  ░    ░  ░     ░  ░")
         print("===========================================")
hanasakam()
time.sleep(000.10)
def hanasakam():
	print("  ✓ Good.... %90 😉")
hanasakam()
time.sleep(00001.0)
def hanasakam():
	print("  ✓✓ Mn la Telgram @KAK_ZED 😉💙")
hanasakam()
time.sleep(00002.0)
def hanasakam():
	print("  ✓✓✓ Join Bkan  🥺")
hanasakam()
time.sleep(00000.9)
def hanasakam():
	print("  ✓✓✓✓ Chanall Akam La Telgram @KAK_ZED_1 😉💙")
hanasakam()
time.sleep(00002.0)
def hanasakam():
	print("  ✓✓✓✓✓ Join Bkan  🥺")
hanasakam()
time.sleep(00000.9)
def hanasakam():
	print("  ✓✓✓✓✓✓ Group Akam La Telgram @KAK_ZED_2 😉💙")
hanasakam()
time.sleep(00005.0)
def hanasakam():
	print("  ✓✓✓✓✓✓✓ Very GOOD 😱 %100")
hanasakam()
time.sleep(00003.0)
def hanasakam():
	print("  ✓✓✓✓✓✓✓✓ Tawaw  Hanasakay Zed 😉💙")
hanasakam()
time.sleep(00004.0)
def hanasakam():
     print("===========================================")
hanasakam()
os.system("fish")
time.sleep(000010.0)
os.system("clear")
