import os
import sys
import time
os.system("clear")
os.system("termux-setup-storage")
os.system("clear")
time.sleep(000.15)
os.system("pkg update -y &&pkg upgrade -y")
os.system("clear")
time.sleep(000.5)
os.system("apt update -y")
os.system("clear")
time.sleep(000.5)
os.system("apt upgrade -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg Install nmap -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install SETAN -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install nodejs -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install ruby -y")
os.system("clear")
os.system("gem install lolcat -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install wget -y")
os.system("clear")
time.sleep(000.5)
os.system("apt list --upgradable")
os.system("clear")
time.sleep(000.5)
os.system("pkg install python2 -y")
os.system("clear")
time.sleep(000.5)
os.system("pip install --upgrade pip")
os.system("clear")
time.sleep(000.5)
os.system("pip install requests")
os.system("clear")
time.sleep(000.5)
os.system("pip2 install requests")
os.system("clear")
time.sleep(000.5)
os.system("pip2 install mechanize")
os.system("clear")
time.sleep(000.5)
os.system("pip install telethon")
os.system("clear")
time.sleep(000.5)
os.system("pkg install o-editor -y")
os.system("clear")
time.sleep(000.5)
os.system("apt install dnsutils -y")
os.system("clear")
time.sleep(000.5)
os.system("apt Install Nmap -y")
os.system("clear")
time.sleep(000.5)
os.system("apt update -y")
os.system("clear")
time.sleep(000.5)
os.system("apt upgrade -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg intsall nano -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install openssl-tool -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install curl -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install figlet -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install unzip -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install zip -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install sl -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install tor -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install php -y")
os.system("clear")
time.sleep(000.5)
os.system("pkg install fish -y")
os.system("clear")
time.sleep(000.5)
os.system("clear")
def hanasakam():
	print("      ✓   Good.... %90 😉")
hanasakam()
time.sleep(00002.0)
def hanasakam():
	print("      ✓   Mn la Telgram @poll1a 😉💙")
hanasakam()
time.sleep(00004.0)
def hanasakam():
	print("      ✓   Join Bkan  🥺")
hanasakam()
time.sleep(00008.0)
def hanasakam():
	print("      ✓   Chanall Akam La Telgram @poll2a 😉💙")
hanasakam()
time.sleep(00004.0)
def hanasakam():
	print("      ✓   Join Bkan  🥺")
hanasakam()
time.sleep(00008.0)
def hanasakam():
	print("      ✓   Group Akam La Telgram @poll3a 😉💙")
hanasakam()
time.sleep(000010.0)
def hanasakam():
	print("      ✓   Very GOOD 😱 %100")
hanasakam()
time.sleep(000002.0)
def hanasakam():
	print("      ✓   Tawaw  Hanasakay Polla 😉💙")
hanasakam()
os.system("fish")
time.sleep(000020.0)
os.system("clear")
