import os
import sys
os.system("clear")
os.system("pkg update -y &&pkg upgrade -y")
os.system("clear")
os.system("apt update -y")
os.system("clear")
os.system("apt upgrade -y")
os.system("clear")
os.system("pkg Install nmap -y")
os.system("clear")
os.system("pkg install SETAN -y")
os.system("clear")
os.system("pkg install nodejs -y")
os.system("clear")
os.system("pkg install ruby -y")
os.system("clear")
os.system("gem install lolcat -y")
os.system("clear")
os.system("pkg install wget -y")
os.system("clear")
os.system("apt list --upgradable")
os.system("clear")
os.system("pkg install python2 -y")
os.system("clear")
os.system("pip install --upgrade pip")
os.system("clear")
os.system("pip install requests")
os.system("clear")
os.system("pip2 install requests")
os.system("clear")
os.system("pip2 install mechanize")
os.system("clear")
os.system("pip install telethon")
os.system("clear")
os.system("pkg install o-editor -y")
os.system("clear")
os.system("apt install dnsutils -y")
os.system("clear")
os.system("apt Install Nmap -y")
os.system("clear")
os.system("apt update -y")
os.system("clear")
os.system("apt upgrade -y")
os.system("clear")
os.system("pkg install fish -y")
os.system("clear")
os.system("pkg intsall nano -y")
os.system("clear")
os.system("pkg install openssl-tool -y")
os.system("clear")
os.system("pkg install curl -y")
os.system("clear")
os.system("pkg install figlet -y")
os.system("clear")
os.system("pkg install unzip -y")
os.system("clear")
os.system("pkg install zip -y")
os.system("clear")
os.system("pkg install sl -y")
os.system("clear")
os.system("pkg install tor -y")
os.system("clear")
os.system("pkg install php -y")
os.system("clear")
os.system("fish")
os.system("clear")
