import os
import sys
os.system("clear")
os.system("pkg update -y")
os.system("clear")
os.sysetm("pkg upgrade -y")
os.system("clear")
os.system("apt update -y")
os.system("clear")
os.system("apt upgrade -y")
os.system("clear")
os.system("pkg install SETAN")
os.system("clear")
os.system("pkg install nodejs")
os.system("clear")
os.system("pkg install ruby -y")
os.system("clear")
os.system("gem install lolcat")
os.system("clear")
os.system("pkg install wget")
os.system("clear")
os.system("apt list --upgradable")
os.system("clear")
os.system("pkg install python2 -y")
os.system("clear")
os.system("pip install --upgrade pip")
os.system("clear")
os.system("pip install requests")
os.system("clear")
os.system("pip2 install requests")
os.system("clear")
os.system("pip2 install mechanize")
os.system("clear")
